name: Publish @lotus-tree/types

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: yarn

      - name: Build app
        run: |
          yarn --frozen-lockfile
          yarn build:app

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKER_USERNAME }}/lotus-tree

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}

  build-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: yarn

      - name: Build types
        run: |
          yarn --frozen-lockfile
          yarn build:types

      - name: Prepare types
        run: |
          mv package.json package-app.json
          cp package-types.json dist/package.json
          cd dist
          YARN_VERSION_GIT_TAG='' yarn version --patch
          cd ..
          rm package-types.json
          cp dist/package.json package-types.json

      - name: Commit new version
        run: |
          git add package-types.json
          git commit -m "Bumped types version"
          git push

      - name: Publish types
        run: |
          cd dist
          npm publish
